version: "3.7"
services:
  #outro container --- backend
  springweb:
    container_name: ecommerce
    build: . #preciso do Dockerfile para gerar a imagem
    ports:
      - "8081:8080"
    networks:
      - servers
    environment:
      SPRING_PROFILES_ACTIVE: docker

networks:
  servers:
    driver: bridge